name: workflow1
on: workflow_dispatch
jobs:
  First-job:
  runs-on: ubuntu-latest
  steps:
  - name: Write a multi-line message
    run: |
      echo This demo file shows a 
      echo very basic and easy-to-understand workflow.
